#! /bin/sh

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd & 

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus 	 true

# --- Colors from Wal

. "${HOME}/.cache/wal/colors.sh"

bspc config active_border_color "$foreground"
bspc config normal_border_color "$color8"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "$color14"

# --- Autostart

# Feh
~/.fehbg &

# Compositors
#pgrep -x picom > /dev/null || picom &
pgrep -x flashfocus > /dev/null || flashfocus &

# Polybar

# --- TODO Set workstations up

eww open bar
# ~/.config/polybar/launch.sh
# bspc config top_padding 28

# bspc config pointer_motion_interval 20

# --- Here come them rules!

bspc rule -a mpv state=floating sticky=on follow=off focus=on 

bspc rule -a feh state=floating sticky=off follow=off center=true rectangle=640x360+0+0

bspc rule -a firefox:Toolkit sticky=on state=floating rectangle=480x270+1424+38

bspc rule -a 'YouTube Music' sticky=on state=floating rectangle=990x660+10+38

bspc rule -a eww-bar layer=below

# --- Mic filter for noise, prolly bind this to app start rather than autostart
# TODO Fix, bugs audio, no output
easyeffects -l VOIP --gapplication-service & disown   
