#! /bin/sh

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

btops &
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus 	 true

#colors

. "${HOME}/.cache/wal/colors.sh"

bspc config active_border_color "$foreground"
bspc config normal_border_color "$color8"
bspc config focused_border_color "$foreground"
bspc config presel_feedback_color "$color3"

# autostart
~/.fehbg &

~/.config/polybar/launch.sh &
~/.config/bspwm/hideAway.sh &
hideIt.sh -N 'polybar-example_HDMI2' -t 

pgrep -x picom > /dev/null || picom &
pgrep -x flashfocus > /dev/null || flashfocus &

kitty &

bspc rule -a mpv state=floating sticky=on follow=off focus=on 

bspc rule -a feh state=floating sticky=off follow=off center=true rectangle=640x360+0+0

bspc rule -a firefox:Toolkit sticky=on state=floating rectangle=480x270+1424+38

bspc config ignore_ewmh_focus true
